name: test_IAMReX
run-name:  IAMReX/test_IAMReX.py is running by ${{ github.actor }} 🚀
on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟运行一次
  push:
jobs:
  test-IAMReX:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: List and pwd
        run: |
          ls /home/runner/work
          echo "------------"
          ls /home/runner/work/IAMReX
          echo "------------"  
      - name: Install MPI
        run: |
          sudo apt update
          sudo apt install -y openmpi-bin openmpi-common libopenmpi-dev
      - name: Clone AMReX and AMReX-Hydro repositories
        run: |
          cd /home/runner/work/IAMReX
          git clone https://github.com/AMReX-Codes/amrex.git
          git clone https://github.com/AMReX-Fluids/AMReX-Hydro.git         
      - name: Run IAMReX tests
        run: |
          cd /home/runner/work/IAMReX/IAMReX
          python Test_IAMReX/test_IAMReX.py
      - name: Finished.
        run: |
          echo "Tests completed!"